language: python
sudo: false
cache:
- pip
python:
- '2.7'
- '3.4'
- '3.5'
install:
- pip install --upgrade pip
- pip install -r requirements-dev.txt
before_script:
- npm i remark remark-lint markdown-spellcheck  -g
script:
- isort --check-only --recursive --diff .
- flake8 --jobs=2 .
- pydocstyle --verbose --explain --source --count
- mdspell --en-us -ran "**/*.md"
- remark -f "**/*.md"
after_success:
- coveralls
deploy:
  provider: pypi
  user: codingjoe
  password:
    secure: QqhABDfAC8bTJMs2geNFAFjNrH3iojVXARa03AiTqRkQNu6/cDGX8FtwTJDEgyh4qd1YxGUimjqsPSvTZYxe60eXgNPQIdPrPvMIDTfq1kn+A6sDuGMuCA352ftfnS2uUVbOk4K/GuZ7l1+YceBZdrt2K80zS9eMIngCMtIci3wFLZ0SUEOBNz6Sk+K2cz7+z6KLEHwZWMuXNuypzEPx0NPWtPJAni9HvaEGQh9DKRVPWJYl35IRIziypNh5ERPO1bqRfcHyIly7guJgAly44xBJjXXAUAPyGqEbA3i6pJxYwGUs8dtsmIrSCx/h9SkSinTHE75N80nDN8vZ6yKxe8HbHn9bGgkGsMpLfJdhNWegb7Sb9i6SwQpJQz779d55oAh3Fv+WVewcMeruWtGlAVqWvjO9W9OKRrcedmlhOZ0ScSHWxgY1/H8d8FVjvWDNHtQV/NcnTMPbMPyycuLSs94Xe43DFplOSUKUX1s1bWmChgTpDbJtTtzP42G/Vpo7ne9rlicoSjx4b9ntRwVkicUGmQx7oDOtb3YsSpGIGL0NZ2oT1TyhqiStCe+JfZ7ZouoAwRjRHFebKfPPToVfjg5qjIXvrc6GSYwlc1c1wBcIsKjjY53dOD7IiT+JCabtnnRiT5JlAAV2YlScx7+yrDXE6jj7ww1IjtOS3UpjcLo=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: codingjoe/django-cc
